In [272]:
"""
Скрипт для подсчета среднего балла для отделений и специальностей
"""

'\nСкрипт для подсчета среднего балла для отделений и специальностей\n'

In [273]:
import pandas as pd
import openpyxl
import time
from openpyxl.utils.dataframe import dataframe_to_rows

In [274]:
def dogovor_spec(type_dog,spec):
    """
    функция для добавления Слова Договор в название направления подготовки если в строке есть слово по договору
    """
    if type_dog == 'по договору':
        return f'Договор {spec}'
    else:
        return spec

In [275]:
ab_df = pd.read_excel('data/Абитуриенты.xlsx',sheet_name='Абитуриенты',skiprows=8,dtype={'ИНН':str,'Серия УЛ':str,'Номер УЛ':str})

In [276]:
fis_df = pd.read_excel('data/Данные по заявлениям с ФИС-ГИА 21.08.xlsx')

In [277]:
fis_df

                               Направление подготовки  Заявлений
0   08.01.31 Электромонтажник электрических сетей ...         58
1   15.01.05 Сварщик (ручной и частично механизиро...        120
2   15.01.33 Токарь на станках с числовым программ...         85
3                     15.01.35 Мастер слесарных работ         61
4                        23.01.09 Машинист локомотива        191
5   23.01.10 Слесарь по обслуживанию и ремонту под...        107
6   23.01.17 Мастер по ремонту и обслуживанию авто...         85
7   35.01.27 Мастер сельскохозяйственного производ...         24
8    43.01.06 Проводник на железнодорожном транспорте         79
9   08.02.09 Монтаж, наладка и эксплуатация электр...         51
10            13.02.07 Электроснабжение (по отраслям)         57
11  23.02.06 Техническая эксплуатация подвижного с...         46
12  23.02.07 Техническое обслуживание и ремонт дви...         52
13  43.02.06 Сервис на транспорте (по видам трансп...         64
14  Договор 43.02.06 Сервис на транспорте (по вида...         14
15      Договор 38.02.02 Страховое дело (по отраслям)         16

In [278]:
# подсчитываем количество заявлений и конкурс
lst_code = ['23.01.09','43.01.06','23.02.06','43.02.06','15.01.05','15.01.35','15.01.33','23.01.10'
    ,'08.01.31','23.01.17','08.02.09','23.02.07','13.02.07','35.01.27','Договор','Договор']

lst_name_spec = ['Машинист локомотива','Проводник на железнодорожном транспорте','Техническая эксплуатация подвижного состава железных дорог',
                 'Сервис на транспорте (по видам транспорта)','Сварщик (ручной и частично механизированной сварки (наплавки)',
                 'Мастер слесарных работ','Токарь на станках с числовым программным управлением','Слесарь по обслуживанию и ремонту подвижного состава'
    ,'Электромонтажник электрических сетей и электрооборудования','Мастер по ремонту и обслуживанию автомобилей',
                 'Монтаж, наладка и эксплуатация электрооборудования промышленных и гражданских зданий',
                 'Техническое обслуживание и ремонт двигателей, систем и агрегатов автомобилей','Электроснабжение (по отраслям)',
                 'Мастер сельскохозяйственного производства','43.02.06 Сервис на транспорте (по видам транспорта)','38.02.02 Страховое дело (по отраслям)']

lst_plan = [100,25,25,25,50,25,50,50
    ,25,25,25,25,25,25,25,25]
base_df = pd.DataFrame(columns=['Код','Наименование'])
base_df['Код'] = lst_code
base_df['Наименование'] = lst_name_spec
base_df['Направление подготовки'] = base_df['Код'] + ' ' + base_df['Наименование']
base_df['База'] = '9 кл.'
base_df['Количество мест'] = lst_plan



dog_df = ab_df.copy()

In [279]:
base_df.drop(columns=['Код','Наименование','База'],inplace=True)
base_df.rename(columns={'Количество мест':'КЦП'},inplace=True)

In [280]:
base_df

                               Направление подготовки  КЦП
0                        23.01.09 Машинист локомотива  100
1    43.01.06 Проводник на железнодорожном транспорте   25
2   23.02.06 Техническая эксплуатация подвижного с...   25
3   43.02.06 Сервис на транспорте (по видам трансп...   25
4   15.01.05 Сварщик (ручной и частично механизиро...   50
5                     15.01.35 Мастер слесарных работ   25
6   15.01.33 Токарь на станках с числовым программ...   50
7   23.01.10 Слесарь по обслуживанию и ремонту под...   50
8   08.01.31 Электромонтажник электрических сетей ...   25
9   23.01.17 Мастер по ремонту и обслуживанию авто...   25
10  08.02.09 Монтаж, наладка и эксплуатация электр...   25
11  23.02.07 Техническое обслуживание и ремонт дви...   25
12            13.02.07 Электроснабжение (по отраслям)   25
13  35.01.27 Мастер сельскохозяйственного производ...   25
14  Договор 43.02.06 Сервис на транспорте (по вида...   25
15      Договор 38.02.02 Страховое дело (по отраслям)   25

In [281]:
base_df=base_df.merge(fis_df,left_on='Направление подготовки',right_on='Направление подготовки',how='outer') # соединяем

In [282]:
base_df

                               Направление подготовки  КЦП  Заявлений
0                        23.01.09 Машинист локомотива  100        191
1    43.01.06 Проводник на железнодорожном транспорте   25         79
2   23.02.06 Техническая эксплуатация подвижного с...   25         46
3   43.02.06 Сервис на транспорте (по видам трансп...   25         64
4   15.01.05 Сварщик (ручной и частично механизиро...   50        120
5                     15.01.35 Мастер слесарных работ   25         61
6   15.01.33 Токарь на станках с числовым программ...   50         85
7   23.01.10 Слесарь по обслуживанию и ремонту под...   50        107
8   08.01.31 Электромонтажник электрических сетей ...   25         58
9   23.01.17 Мастер по ремонту и обслуживанию авто...   25         85
10  08.02.09 Монтаж, наладка и эксплуатация электр...   25         51
11  23.02.07 Техническое обслуживание и ремонт дви...   25         52
12            13.02.07 Электроснабжение (по отраслям)   25         57
13  35.01.27 Мастер сельскохозяйственного производ...   25         24
14  Договор 43.02.06 Сервис на транспорте (по вида...   25         14
15      Договор 38.02.02 Страховое дело (по отраслям)   25         16

In [283]:
#count_df.groupby(by=['Направление подготовки']).agg({'ФИО':'count'})

In [284]:
ab_df = ab_df[ab_df['Состояние выбран. конкурса'] == 'Зачислен'] # оставялем только зачисленных
ab_df['Направление подготовки'] = ab_df.apply(lambda row: dogovor_spec(row['Вид возмещения затрат'],row['Направление подготовки']),axis=1)

replace_dct = {'Отделение железнодорожного транспорта':'ЖД','Отделение металлообработки':'МО',
               'Отделение энергоснабжения':'ЭО','Хоринский филиал':'ХФ',}

ab_df['Формирующее подр.'] = ab_df['Формирующее подр.'].replace(replace_dct)

unit_lst = ab_df['Формирующее подр.'].unique()

dct_unit = {key:None for key in unit_lst}

In [285]:
avg_df = ab_df[['ФИО','Ср. балл док-та об образовании','Формирующее подр.','Направление подготовки']] #  отбираем нужные колонки

In [286]:
for name in unit_lst:
    temp_df = avg_df[avg_df['Формирующее подр.']== name]
    temp_df = pd.pivot_table(temp_df,index = ['Направление подготовки'],
                            values=['Ср. балл док-та об образовании'],
                            aggfunc={'Ср. балл док-та об образовании':'mean'}
                           )
    temp_df.columns = ['Средний балл зачисленных']
    temp_df['Средний балл зачисленных'] = temp_df['Средний балл зачисленных'].apply(lambda x:round(x,2))
    temp_df = temp_df.reset_index()
    temp_df = temp_df.merge(base_df,left_on='Направление подготовки',right_on='Направление подготовки')
    temp_df['Конкурс'] = round(temp_df['Заявлений'] / temp_df['КЦП'],2)
    
    
    dct_unit[name] = temp_df

In [287]:
dct_unit['ЖД']['Направление подготовки']= dct_unit['ЖД']['Направление подготовки'].apply(lambda x:x.replace('23.01.09 Машинист локомотива','23.01.09 Помощник машиниста (по видам подвижного состава железнодорожного транспорта)'))

In [288]:
t = time.localtime()
current_time = time.strftime('%H_%M_%S', t)

wb = openpyxl.Workbook()
# Переименовываем лист
sheet = wb['Sheet']
sheet.title = 'ЖД'
wb.create_sheet('МО',index=1)
wb.create_sheet('ЭО',index=2)
wb.create_sheet('ХФ',index=3)

for name,df in dct_unit.items():    
    for r in dataframe_to_rows(df,index =False,header=True):
        if len(r) != 1:
            wb[name].append(r)

for name in unit_lst:
    wb[name].column_dimensions['A'].width =70
    wb[name].column_dimensions['B'].width =20
    wb[name].column_dimensions['C'].width =20
    wb[name].column_dimensions['D'].width =30
    wb[name].column_dimensions['D'].width =20


# Сохраняем итоговый файл
wb.save(f'data/Отчет заявления,средний балл от {current_time}.xlsx')

In [289]:
# высчитываем договорников

dog_ser_df = pd.read_excel('data/Договор Сервис на транспорте.xlsx') # сервис на транспорте
dog_fear_df = pd.read_excel('data/Договор Страховое дело.xlsx') #  страховое

dog_df = dog_df[['ФИО','Ср. балл док-та об образовании']]

dog_df

df = pd.concat([dog_ser_df,dog_fear_df],ignore_index=True)

df

out_df=df.merge(dog_df,left_on='ФИО',right_on='ФИО',how='inner')

out_df.drop_duplicates('ФИО',inplace=True)

out_df

out_df=out_df.groupby('Направление подготовки').agg({'Ср. балл док-та об образовании':'mean'})

out_df['Ср. балл док-та об образовании']= out_df['Ср. балл док-та об образовании'].apply(lambda x:round(x,2))

out_df.to_excel('data/Договорники средний балл.xlsx')